### ISSUE TITLE
AV Balancing

### ISSUE THREAD

**Issue by TinyTurtles123** [paradigmnomad/PPJA#1]
- Absinthe can be bought for 120 but sells for 405
- The speed buff on drinks from the Espresso Machine is way to high- Coffee's +1, most from the Espresso Machine are +10 or more

**Comment by minervamaga** [comment]
Another comment about balancing: https://forums.nexusmods.com/index.php?showtopic=6430601/#entry73703263

**Comment by TimeWandrer** [comment]
All of the cannabis stuff should be looked over for balancing.

**Comment by paradigmnomad** [comment]
Upcoming version:

Absinthe values have been swapped. It can now be purchased for 405 and sold for 120.
Espresso Machine recipes have been rebalanced to either 1-2 speed buff.
Elderberry price has been reduced (60 down to 20), crop production reduced (Max 5 drops to Max 3), and chance to get extra drops reduced (.2 down to .1).
Schnapps value has been decreased from 600 to 300.
