### ISSUE TITLE
Suggestion: Update Key

### ISSUE THREAD

**Issue by DiscoverSquishy** [paradigmnomad/PPJA#100]
Hi,

In Khadija's Recipe Shop, there is no Update Key.
Adding it would be helpful for us to know if there is an update & to essentially get rid of the extra reminder to remind the author of the mod to add the update key.

Thanks.

**Comment by paradigmnomad** [comment]
In the latest version from Nexus the update key is inside the STF component - that way you don't get 4 separate update notifications for the same mod since everything is bundled together into one mod page ID.
