### ISSUE TITLE
Nuts

### ISSUE THREAD

**Issue by Rametteperegrine** [paradigmnomad/PPJA#101]
I looked at Mousey's list and I don't see any artisan goods that can be done with some of the nuts. Pistachio, pine, and Macadamia at least. Can we make them into nut butter or roast them? Maybe in the furnace?

**Comment by paradigmnomad** [comment]
Those items aren't included in any of the PPJA collection (unless this is a suggestion to add them). It would be up to the original author to add the ability to make them into nut butter or roast them. PPJA does have a small assortment of nuts that can be turned into butters.

**Comment by Rametteperegrine** [comment]
Huh, I guess I got them with a different mod. sorry about that
