### ISSUE TITLE
I made some Recipes

### ISSUE THREAD

**Issue by Al4000in** [paradigmnomad/PPJA#117]
I honestly do not get how this site works but I made some recipes and I post them here. I made a Toast recipe as basis for Toast hawaii and toast williams, I would suggest to replace the bread used in avocado toast too with toast. I did somewhat adjust prices and edibility but I don't really know how to balance. Feel free to use them as you want I would be honored. It was fun I might make more if appreciated. Would appreciate a short feedback.

(I made the sprites and the .json I'm native german so I made the de translation too)
  
[New 4.6.2020.zip](https://github.com/paradigmnomad/PPJA/files/4440577/New.4.6.2020.zip)

**Comment by paradigmnomad** [comment]
Thanks for making these! I'm finally getting around to adding them to EMR/Fresh Meat in their next updates. The biggest thing with these was the high color count. SDV sprites usually only use around 8 colors and some of these had 30+ that were all very similar. I tweaked them to reduce the color count and improve the outline on the Toast-sprites and the ramekins.
