### ISSUE TITLE
Minor Mod QOL Suggestion

### ISSUE THREAD

**Issue by Lodemeer** [paradigmnomad/PPJA#160]
Suggesting if there is any way to make a Mod to identify the missing items in the shipping tab? Unfortunately I installed the mega pack before achieving the  A Full Shipment Achievement and i now have to find each every PPJA item huhuu

**Comment by minervamaga** [comment]
Already exists: https://www.nexusmods.com/stardewvalley/mods/4430
Mod suggestions do not belong here, please use the correct repo.
