### ISSUE TITLE
Minor Korean translation issue about Green Beans and Green Peas

### ISSUE THREAD

**Issue by HaxtonSale1** [paradigmnomad/PPJA#163]
As I know, the official Korean translation for the [Green Bean](https://stardewvalleywiki.com/Green_Bean) [(in which we eat the bean pods)](https://en.wikipedia.org/wiki/Green_bean) is "완두콩" which actually translates to "Green Peas". The Korean translation for [Green Peas](https://github.com/paradigmnomad/PPJA/blob/aa2ae7f275fc6f637153982edbcdcf474af66c96/%5BPPJA%5D%20Fruits%20and%20Veggies/%5BJA%5D%20Fruits%20and%20Veggies/Objects/Green%20Peas/object.json) became "그린 피스" to avoid collision, which is just the transliteration of "Green Peas", which sounds awkward when there's a proper translation, "완두콩" (Besides Google thinks 그린 피스 actually means Greenpeace (The organization)). I would have fixed it otherwise, but the official translation is the problem.

**Comment by paradigmnomad** [comment]
Google Translate often gets confused which is why we don't rely on it (Greenpeace is a perfect example of this), We have two native Korean speakers who help with our translations and I'll pass this onto them to get their feedback.

**Comment by HaxtonSale1** [comment]
I've already sent a mail to Concernedape about this, so hopefully he replies to me.
