### ISSUE TITLE
Items appearing as the wrong item

### ISSUE THREAD

**Issue by Bparks5896** [paradigmnomad/PPJA#188]
Coal seeds are being picked as gold seeds on my side and beef on the other player's side.

**Comment by paradigmnomad** [comment]
This is not an issue with PPJA but JA. Sometimes item IDs get scrambled when adding/removing packs. The solution is to remove the items that are appearing wrong and spawn them back in with CJB Item Spawner. It's a pain but it's the only consistent solution.
