### ISSUE TITLE
Suggestion for unlocking Machines based on Skill level - Artisan Valley

### ISSUE THREAD

**Issue by Logicsol** [paradigmnomad/PPJA#21]
Playing with AV has been great for the expanded variety, but starting a new game the craft tab is a bit, overwhelming and incongruous. 

I suggest unlocking the machines at certain skill levels or events, and spent some time looking at the progression of vanilla machines to make this list:

[JA-VA suggested Machine Tiers.txt](https://github.com/paradigmnomad/PPJA/files/3919867/JA-VA.suggested.Machine.Tiers.txt)

Thanks for your time!

**Comment by paradigmnomad** [comment]
We've always wanted to do this but with the limitations we can't add them based on skill unlock. I'll keep the list you made as I like where you've placed machines if we're ever able to add skill based unlocks!

**Comment by paradigmnomad** [comment]
With the migration to PFM we were able to add skill-based unlocks. These suggestions were taken into account when coming up with skill unlock levels so thank you :)
