### ISSUE TITLE
Suggestion: Lower Profit Margin Option

### ISSUE THREAD

**Issue by gabrielsubzero** [paradigmnomad/PPJA#234]
Hey there! I realised while playing SVE that the lower profit margin option in that mod is really fun and interesting, as it makes so my gradual building of wealth isn't so sudden (especially with mods like farming made easy).

I was wondering if it would be possible to add a option to this mod that would cut down the sell price by 20% of all crops, I managed to do it myself but it took about an hour to fix all the values, as I had to edit each file manually, all those changes would go away once I updated the mod.

Thank you for the awesome mod!

**Comment by paradigmnomad** [comment]
With how JA is that'd basically require a whole nother PPJA with a 20% decrease in profit margin, as you noticed by having to manually edit the files. You can use a mod like [Profit Margins](https://www.nexusmods.com/stardewvalley/mods/4663). I don't use it myself but that mod should work on custom objects.

**Comment by gabrielsubzero** [comment]
That's a shame, I thought you could add like a variable that would do that work for you, I might try that mod then, more annoying but I suppose it works.
