### ISSUE TITLE
crop discrepancies

### ISSUE THREAD

**Issue by metalax** [paradigmnomad/PPJA#25]
Was bamboo meant to be a paddy crop? It was made into one with the 1.4 changes, but then lost it when the translations were put in.

Adzuki Bean growth stages give  9 days, description 10.
Bamboo growth stages give  7 days, description 5.
Cotton growth stages give  7 days, description 6.
Soybean growth stages give 9 days, description is 10.
Zucchini growth stages give 14 days, description is 12.

Bamboo description missing that it regrows.

**Comment by paradigmnomad** [comment]
Bamboo is meant to be a paddy crop! It must have gotten changed back after a pull request. I will update these descriptions for the next update. I just put out one today but didn't see this until after. Github will be updated with the fixes later tonight.

Thank you for pointing these out! I appreciate it :)

**Comment by paradigmnomad** [comment]
These issues should be resolved in the latest version.
