### ISSUE TITLE
Cannabis Kit Outdated

### ISSUE THREAD

**Issue by weedmodhaver** [paradigmnomad/PPJA#274]
I made a nexus account for your very mod and I am heartbroken to see it is not updated, will it work still? What do I have to do to get you to update it?  I love your work

**Comment by paradigmnomad** [comment]
The mod didn't require any changes for 1.5 so there is no need to update it for 1.5. I do have a beta version that has lots of content the main file doesn't if you want to use that.

**Comment by weedmodhaver** [comment]
> The mod didn't require any changes for 1.5 so there is no need to update it for 1.5. I do have a beta version that has lots of content the main file doesn't if you want to use that.

I would be so honored to try something from you!! Whenever your ready I'll test em out and if you want I can let you know if there are any bugs or test the limits if you want

**Comment by weedmodhaver** [comment]
I added your beta to my game which is on year 4 or 5, but I haven't gotten any of the letters giving me machine recipes.  We all know the Marnie cheat where you buy an animal with the name [107] or whatever number and an item spawns in your inventory, since I probably messed up the mod with my aged file, what is the number to spawn the machines in?
Thank you,
Weedmodlover
