### ISSUE TITLE
Winter crops get removed

### ISSUE THREAD

**Issue by Lechloan** [paradigmnomad/PPJA#279]
Im playing 64-bit Stardew and have Fantasy Crops and Fruit and Veggies installed. unfortunately when planting Juniper Berries, Mint or Iridium in Winter they get removed like vanilla crops the next days.
Smapi-log: https://smapi.io/log/d5d1a9612078401293d194fb92834694

**Comment by Geethebluesky** [comment]
Came to report the same issue. I only have the Fruits and Veggies mod but my mint just keeps getting removed day after day.

Didn't happen before I switched to 64 bit version but I needed to due to too many mods and out of memory errors.

**Comment by Lechloan** [comment]
The issue was apparently with SpaceCore, updatimg to the newest update here: https://github.com/pepoluan/StardewValleyMods/releases Fixed the issue.

**Comment by Pathoschild** [comment]
(That's an unofficial update, but it'll be fixed officially in the upcoming Json Assets 1.7.7 and SpaceCore 1.5.7.)
