### ISSUE TITLE
Having Trouble with Mizu's Flowers

### ISSUE THREAD

**Issue by jriley925** [paradigmnomad/PPJA#281]
I am hoping that you might be able to help me and also that you should know. I have multiple stored flowers that are being overwritten by another mod (I believe). Here is the post I entered on Baker's Life:

June 6: I just installed 2 new mods, Chocolatier and Baker's Life, and while I would love to use them, there are several flowers that have been changed or replaced. In my flowers1 folder, my Chayote flowers now have a picture of the seed instead of the flowers. In the same folder, I had three other varieties of flowers that now say they are Duckvine Seeds, Golden Tigerseye Faberge, and Red Onion Seeds although each still has the categroy of "Flower". I'm sorry but I don't remember what the original flower was. In my Flowers2 folder, there are Chayote seeds again - I don't think I had Chayote in two different folders although I can't be sure. If I didn't that means yet anpther flower was overwritten. Also, my Spring Rose flowers have been changed to a picture of the seed just like the Chayote and another flower has been changed to Double Chocolate Gelato, again not sure what the original flower was. In my Flowers3 folder, two flowers have been overwritten and are now Baker's Lemon Coconut Cake and Persimmon Pudding.

As I said, I installed 2 mods and both were created by this mod author. I am not sure which mod is causing the issue.

June 12: So, I thought that I maybe I shouldn’t have said anything because it looked like the other flowers I grew were doing fine and it was only the ones I had stored in chests that were affected. I was wrong. I have gone through a couple of more seasons and grown more flowers, stored them in chests, and things were fine – until I restarted. Now, I have more strange products taking the place of my flowers. It seems to be the flowers from Mizu’s Flowers. I know I had these flowers – Fairy Duster, Purple Coneflower, Bee Balm, and Shaded Violet. Even the honey that I made from Rafflesia has been affected by the image changing on the honey. The products that replaced my flowers are different this time – Schnapps, Sulfur Shelf Mushroom, Barley Kombucha, Enchanted Golden Diamond Faberge, and Porter.
I have only installed 3 new mods recently, so I assume one of these mods is the culprit. They are Baker’s Life, Chocolatier, and SOJA Ancient Crops.

I am not sure what information you might want to investigate the issue. Please let me know.

**Comment by zwei7** [comment]
Hello
I am also having my flowers in my Small Storage Shed being replaced by the different items.
Fragrant Lilac is now Frgrant Lilac Bulb.
My Herbal Lavender turned into Herbal Lavender seeds.
Lavender is now Lavender Cream Soda.
Lily is reverting to Lily Bulb.

What is really screwy is the Herbal Lavendar Seeds.
My Herbal Lavender turned into **Herbal Lavender seeds** (worth 30g).
My **Herbal Lavendar seeds** I buy from Pierre are a different icon and worth (30g).
