### ISSUE TITLE
Krobus does not sell modded seeds after you "marry" him

### ISSUE THREAD

**Issue by HaxtonSale1** [paradigmnomad/PPJA#283]
The chest that replaces him after you marry him does not sell Fantasy Crops seeds, nor it sells Dragon/Phoenix meat seeds

**Comment by Pathoschild** [comment]
Can you attach a zip of [your save folder](https://stardewvalleywiki.com/Saves) so I can reproduce it?

**Comment by HaxtonSale1** [comment]
Could it be a mod interaction issue? I did installed some non-ppja mods

**Comment by Pathoschild** [comment]
It's possible, but there's a change in the latest Json Assets 1.8.0 that might be causing it.

**Comment by HaxtonSale1** [comment]
[Hilltop_282145961.zip](https://github.com/paradigmnomad/PPJA/files/6852425/Hilltop_282145961.zip)

**Comment by Pathoschild** [comment]
It's not related to Json Assets 1.8.0, but I added a fix in the upcoming 1.8.2. Thanks for reporting it!
