### ISSUE TITLE
Cotton as a fruit doesn't make sense

### ISSUE THREAD

**Issue by DarkYuan** [paradigmnomad/PPJA#284]
Cotton can be made into jelly and wine, along with other mods that accept fruit like dried fruit in the dehydrator, fruit juice in the juicer. Maybe it would fit better under the resource or forage tags if that's possible; even flower might work.

**Comment by paradigmnomad** [comment]
It has changed category a few times, but technically the cotton boll is a fruit. [Source](https://cottonaustralia.com.au/assets/general/Education-resources/CA-resources/CEK_Chap_4_The_Cotton_Plant.pdf). I would never have considered it a fruit.
