### ISSUE TITLE
(Mizu's Flowers) Consider gating Rose to year 2

### ISSUE THREAD

**Issue by saltyseadoggo** [paradigmnomad/PPJA#288]
Regular rose crops grow through all three seasons. The only vanilla crop to do this is the ancient fruit, whose rare nature gates it to later on, especially in large quantities. While the rose is nowhere near as valuable as the ancient fruit, I feel that having it available immediately detracts from the early game emphasis on crop seasons. As such, I would like to suggest gating the availability of rose seeds to year 2, and pushing Haley's letter about it to year two as well.

**Comment by paradigmnomad** [comment]
Thanks for the suggestion. This will be implemented in the next release.
