### ISSUE TITLE
Empty Letters

### ISSUE THREAD

**Issue by xPiink** [paradigmnomad/PPJA#296]
Everyday I open the Ferngill Florists letters and it has all the words, just like, none of the items? 

https://i.gyazo.com/thumb/1200/b160b8833845bdfbbb72b81ae072fc9f-jpg.jpg

**Comment by Contact-Lost** [comment]
I'm having the same problem. No DGA recipes appear in mail.  The SMAPI error I get is something like: 
[Mail Framework Mod] The recipe 'Converted_Estival Tea Recipe' was not found. The mail will ignore it.

**Comment by djfariel** [comment]
Fix for Florist letters in this PR. https://github.com/paradigmnomad/PPJA/pull/300
