### ISSUE TITLE
Items not used in recipes

### ISSUE THREAD

**Issue by TinyTurtles123** [paradigmnomad/PPJA#4]
**These items aren't used in any recipes, crafting, or machines, as far as I can tell. (excluding machines/recipes that accept all herbs, all fruits, etc.)**

Passion Fruit, Elderberry, Basil, Adzuki Bean, Chives, Oregano, Aloe, Rosemary, Sage, Fennel, Spinach

Durian, Mango, Asian Pear, Pomelo, Ylang Ylang

Pink Cat, Shaded Violet, Spring Rose, Clary Sage, Passion Flower, Summer Rose, Bee Balm, Fairy Duster, Fall Rose, Purple Coneflower, Honeysuckle

Some Meat (not sure which)

(F2F)
Delphinium, Hyacinth, Hydrangea, Petunia, Dahlia, Gernaium

**Comment by paradigmnomad** [comment]
This is intentional. Not all crops etc. are going to be used in recipes/crafting.
