### ISSUE TITLE
PPJA Productivity

### ISSUE THREAD

**Issue by TinyTurtles123** [paradigmnomad/PPJA#7]
A list of gold/day for all F&V and Mizu's Flowers crops 
(For reference, Starfruit is 26.92, Blueberries are 20.8, and Cranberries are 18.89)

Rose - 56.1
Navy Bean - 51.6

Honeysuckle - 47.92
Spring, Summer, Fall Rose - 40

Sweet Canary Melon - 39.07
Juniper Berry - 35.8
Watermelon - 33.33
Elderberry - 31.92

Gooseberry - 26.8

Cotton - 18.98
Cucumber - 18.27
Pineapple - 18.13
Kiwi - 16.67
Raspberry - 15
Green Pea - 14.23
Muskmelon - 12.5
Sugar Cane - 12
Aloe - 10
Blue Mist - 10
Sugar Beet - 10

Passion Fruit - 9.26
Rice - 9.04
Passion Flower - 8.75
Bell Pepper - 8.46
Wasabi - 8.13
Soybean - 8
Sweet Jasmine - 7.86
Spinach - 6.67
Rosemary - 6.43
Mint - 6.25
Bee Balm - 6.11
Tea - 6.08
Sage - 6
Broccoli - 5.71
Cabbage - 5.71
Oregano - 5
Parsley - 5
Thyme - 5
Onion - 4.38
Ginger - 4.29
Adzuki Bean - 4
Purple Coneflower - 3.89
Barley - 3.75
Clary Sage - 3.75
Sweet Potato - 3.75
Basil - 3
Chamomile - 3
Chives - 3
Fennel - 3
Cassava - 2.86
Fairy Duster - 2.86
Carrot - 2.5
Celery - 2.5
Peanut - 2.5
Pink Cat - 2.5
Fragrant Lilac - 2.14
Shaded Violet - 1.88
Herbal Lavender - 1.67
Lettuce - 1.67
Blackberry - 1.54

**Comment by paradigmnomad** [comment]
Currently in the process of rebalancing based off this info.
