### ISSUE TITLE
Tea bags

### ISSUE THREAD

**Issue by Rametteperegrine** [paradigmnomad/PPJA#97]
I'm not sure if this is a question or a suggestion but can you make tea from the tea bags the dryer produces? I thought you needed to put them in the glass jars but it looks like they don't go.

**Comment by paradigmnomad** [comment]
Sadly with tea bags those are part of Farmer to Florist and we have strict permissions on what we can and cannot do with their assets/original coding.

However, it does give me an idea of something I could do with the Drying Rack. Let me talk with the others and see if we can come up with anything.
